<a href="https://colab.research.google.com/github/maitreya-v/Colab/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [131]:
import numpy as np
import pandas as pd

In [132]:
import matplotlib.pyplot as plt

In [133]:
import tensorflow as tf

In [134]:
from sklearn.preprocessing import LabelEncoder

In [135]:
bank_df = pd.read_csv('./Churn_Modelling.csv')

In [136]:
bank_df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [137]:
bank_df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [138]:
bank_df.head(10)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   
5          645     Spain    Male   44       8  113755.78              2   
6          822    France    Male   50       7       0.00              2   
7          376   Germany  Female   29       4  115046.74              4   
8          501    France    Male   44       4  142051.07              2   
9          684    France    Male   27       2  134603.88              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0  
5          1               0        149756.71       1  
6          1               1         10062.80       0  
7          1               0        119346.88       1  
8          0               1         74940.50       0  
9          1               1         71725.73       0

In [139]:
lb=LabelEncoder()
bank_df['Gender']=lb.fit_transform(bank_df['Gender'])

In [140]:
bank_df.head(10)
bank_df['Geography'][9998]

'Germany'

In [141]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()

In [142]:
encoder_df = pd.DataFrame(ohe.fit_transform(bank_df[['Geography']]).toarray())

In [143]:
pd.DataFrame(ohe.fit_transform(bank_df[['Geography']]).toarray())

0    1    2
0     1.0  0.0  0.0
1     0.0  0.0  1.0
2     1.0  0.0  0.0
3     1.0  0.0  0.0
4     0.0  0.0  1.0
...   ...  ...  ...
9995  1.0  0.0  0.0
9996  1.0  0.0  0.0
9997  1.0  0.0  0.0
9998  0.0  1.0  0.0
9999  1.0  0.0  0.0

[10000 rows x 3 columns]

In [144]:
bank_df=bank_df.join(encoder_df)

In [145]:
bank_df.drop(columns=['Geography'],inplace=True)

In [146]:
bank_df

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1   
1             608       0   41       1   83807.86              1          0   
2             502       0   42       8  159660.80              3          1   
3             699       0   39       1       0.00              2          0   
4             850       0   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       1   39       5       0.00              2          1   
9996          516       1   35      10   57369.61              1          1   
9997          709       0   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   
9999          792       0   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited    0    1    2  
0                  1        101348.88       1  1.0  0.0  0.0  
1                  1        112542.58       0  0.0  0.0  1.0  
2                  0        113931.57       1  1.0  0.0  0.0  
3                  0         93826.63       0  1.0  0.0  0.0  
4                  1         79084.10       0  0.0  0.0  1.0  
...              ...              ...     ...  ...  ...  ...  
9995               0         96270.64       0  1.0  0.0  0.0  
9996               1        101699.77       0  1.0  0.0  0.0  
9997               1         42085.58       1  1.0  0.0  0.0  
9998               0         92888.52       1  0.0  1.0  0.0  
9999               0         38190.78       0  1.0  0.0  0.0  

[10000 rows x 13 columns]

In [147]:
# France Germany Spain


bank_df.rename(columns={0:'France',1:'Germany',2:'Spain'},inplace=True)
bank_df.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  France  Germany  Spain  
0               1        101348.88       1     1.0      0.0    0.0  
1               1        112542.58       0     0.0      0.0    1.0  
2               0        113931.57       1     1.0      0.0    0.0  
3               0         93826.63       0     1.0      0.0    0.0  
4               1         79084.10       0     0.0      0.0    1.0

In [148]:
y=bank_df['Exited']

In [149]:
bank_df.drop(columns=['Exited'],inplace=True)

In [150]:
X=bank_df

In [151]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [152]:
from sklearn.preprocessing import StandardScaler

In [153]:
sc=StandardScaler()
X_train=sc.fit_transform(X_train)

In [154]:
X_test=sc.transform(X_test)

In [155]:
X_train

array([[-0.34459497, -1.09823226, -0.65674999, ..., -1.00171576,
        -0.57559072,  1.73073215],
       [-0.09518109, -1.09823226, -0.46637979, ..., -1.00171576,
         1.73734559, -0.57779016],
       [-0.94734518,  0.91055421, -0.56156489, ...,  0.99828718,
        -0.57559072, -0.57779016],
       ...,
       [ 0.86090545, -1.09823226, -0.08563939, ...,  0.99828718,
        -0.57559072, -0.57779016],
       [ 0.15423279,  0.91055421,  0.39028611, ...,  0.99828718,
        -0.57559072, -0.57779016],
       [ 0.46600014,  0.91055421,  1.1517669 , ..., -1.00171576,
         1.73734559, -0.57779016]])

In [156]:
y_train=np.array(y_train)
y_test=np.array(y_test)

In [157]:
ann = tf.keras.models.Sequential()

In [158]:
ann.add(tf.keras.layers.Dense(6, activation='relu'))
ann.add(tf.keras.layers.Dense(6, activation='relu'))
ann.add(tf.keras.layers.Dense(1, activation='sigmoid'))

In [159]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [160]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
219/219 [==============================] - 2s 3ms/step - loss: 0.5281 - accuracy: 0.7729
Epoch 2/100
219/219 [==============================] - 1s 3ms/step - loss: 0.4609 - accuracy: 0.7923
Epoch 3/100
219/219 [==============================] - 1s 3ms/step - loss: 0.4398 - accuracy: 0.7924
Epoch 4/100
219/219 [==============================] - 1s 2ms/step - loss: 0.4256 - accuracy: 0.7927
Epoch 5/100
219/219 [==============================] - 1s 2ms/step - loss: 0.4145 - accuracy: 0.7929
Epoch 6/100
219/219 [==============================] - 1s 2ms/step - loss: 0.4043 - accuracy: 0.7931
Epoch 7/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3964 - accuracy: 0.8016
Epoch 8/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3888 - accuracy: 0.8331
Epoch 9/100
219/219 [==============================] - 1s 4ms/step - loss: 0.3827 - accuracy: 0.8407
Epoch 10/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3770 - accura

In [161]:
ann.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 6)                 78        
                                                                 
 dense_4 (Dense)             (None, 6)                 42        
                                                                 
 dense_5 (Dense)             (None, 1)                 7         
                                                                 
Total params: 127
Trainable params: 127
Non-trainable params: 0
_________________________________________________________________


In [167]:
y_preds=ann.predict(X_test)

94/94 [==============================] - 0s 3ms/step


In [168]:
y_preds

array([[0.04977455],
       [0.03524723],
       [0.1019677 ],
       ...,
       [0.05831452],
       [0.00383002],
       [0.10785104]], dtype=float32)

In [169]:
y_test

array([0, 0, 0, ..., 0, 0, 0])

In [186]:
from sklearn.metrics import confusion_matrix

In [171]:
from sklearn.metrics import accuracy_score

In [172]:
y_preds.shape

(3000, 1)

In [175]:
y_preds=y_preds.flatten()

In [182]:

y_preds=(y_preds>0.5).astype(int)
y_preds

array([0, 0, 0, ..., 0, 0, 0])

In [184]:
print(accuracy_score(y_test,y_preds)*100)

86.9


In [187]:
print(confusion_matrix(y_test,y_preds))

[[2342   74]
 [ 319  265]]
